version: '3'
services:
  mongo:
    image: mvertes/alpine-mongo:latest
    expose:
      - "27017"
      - "37017"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      # - MONGODB_USER="user"
      # - MONGODB_PASS="pass"
    volumes:
      - ./volumes/mongodb/data:/data/db:rw
    restart: always
    ports:
      - 27017:27017
    networks:
        sandbox:

  users-server:
    build:
      context: ./users-service/
      dockerfile: Dockerfile
    image: app:users-server
    volumes:
      - ./users-service/:/usr/src/app/:rw
    environment:
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: ${JWT_SECRET}
      SERVER_PORT: ${USERS_PORT}
      WAIT_HOSTS: mongo:27017
    ports:
      - "${USERS_PORT}:${USERS_PORT}"
      - "56748:56748"
    networks:
      sandbox:
    depends_on:
      - mongo
      
  cinema-server:
    build:
      context: ./cinema-service/
      dockerfile: Dockerfile
    image: app:cinema-server
    volumes:
      - ./cinema-service/:/usr/src/app/:rw
    environment:
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: ${JWT_SECRET}
      SERVER_PORT: ${CINEMAS_PORT}
      WAIT_HOSTS: mongo:27017, users-server:${USERS_PORT}
    ports:
      - "${CINEMAS_PORT}:${CINEMAS_PORT}"
      - "56746:56746"
    networks:
      sandbox:
    depends_on:
      - mongo
      - users-server

  movie-server:
    build:
      context: ./movie-service/
      dockerfile: Dockerfile
    image: app:movie-server
    volumes:
      - ./movie-service/:/usr/src/app/:rw
    environment:
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: ${JWT_SECRET}
      SERVER_PORT: ${MOVIES_PORT}
      WAIT_HOSTS: mongo:27017, users-server:${USERS_PORT}
    ports:
      - "${MOVIES_PORT}:${MOVIES_PORT}"
      - "56747:56747"
    networks:
      sandbox:
    depends_on:
      - mongo
      - users-server
networks: 
  sandbox:
    
